name: Build Kahuna Firmwares

on:
  push:
    branches:
      - "UAS-FR-651384"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Install MAVLink dependencies
        run: git submodule update --init --recursive

      - name: Build firmware
        run: pio run -e esp07s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-kahuna
          path: |
            .pio/build/esp07s/firmware.bin
